server.port: 7000

spring:
  application.name: gateway
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mariadb://hiedu.iptime.org:50001/auth
    username: study
    password: study
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none   # 개발중엔 update, 운영은 none/validate 권장
    show-sql: true
    properties:
      hibernate:
        format_sql: true	
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers Access-Control-Allow-Credentials RETAIN_FIRST 
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                    - http://localhost:7000
                    - http://localhost:5173
                    - http://192.168.0.35:5173
                allow-credentials: true
                allowedHeaders: 
                  - '*'
                allowedMethods:
                  - PUT
                  - GET
                  - POST
                  - PATCH
                  - DELETE
                  - OPTIONS
          routes:
            - id: solo-service
              uri: ${ROUTE_SOLO_URI}
              predicates:
                - Path=/solo/**
              filters:
                - RewritePath=/solo/?(?<segment>.*), /${segment}
                - ApiFilter
            - id: oauth-service
              uri: ${ROUTE_OAUTH_URI}
              predicates:
                - Path=/oauth/**
              filters:
                - RewritePath=/oauth/?(?<segment>.*), /${segment}
                - ApiFilter
            - id: openapi
              uri: ${ROUTE_API_URI}
              predicates:
                - Path=/v3/api-docs/**
              filters:
                - RewritePath=/v3/api-docs/?(?<segment>.*), /${segment}/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: gateway
  tracing:
    enabled: false
    sampling:
      probability: 1.0

springdoc:
  swagger-ui:
    # use-root-path: true
    path: /docs
    operationsSorter: method

logging.level.org.springframework: INFO
